### ISSUE TITLE
Urban Dictionary Bugs

### ISSUE THREAD

**Issue by xSilverdroid** [xSilverdroid/Sonico#19] opened 2017-03-08 22:34 UTC
Urban Dictionary still has bugs, even if it's in development state. I noticed two of them so far

1. When no result is found, no error message is shown, even if one is specified in `Sonico.py`  
**This bug is also present in the osu! Integration**

2. The term specified is not showing up in the title of `discord.Embed`

![screenshot 2017-03-08 23 25 36](https://cloud.githubusercontent.com/assets/16563020/23727306/cf568452-0457-11e7-822d-23c6a2b2e0ee.png)

**Comment by runnerbeany** [comment] 2017-03-10 18:56
Maybe @Nevexo can help on this since he wrote this cog. It looks like it doesn't use the same method as the other cogs.

**Comment by Nevexo** [comment] 2017-03-16 21:56
Issues are all caused by Sonico.py, cogs/dict.py provides an error message.

**Comment by Nevexo** [comment] 2017-03-16 22:20
Issues resolved in /dev branch. Closed.

**Closed by Nevexo** 2017-03-16 22:20 UTC
Labels: bug
